name: Notify orchestrator on push

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to orchestrator
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ORCHESTRATOR_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Appraisily/appraisily-workspace/dispatches \
            -d "{\"event_type\":\"service-updated\",\"client_payload\":{\"service\":\"valuer-agent\",\"branch\":\"${{ github.ref_name }}\",\"sha\":\"${{ github.sha }}\",\"repo\":\"${{ github.repository }}\"}}"


